### ISSUE TITLE
Building Application for Student Society

### ISSUE THREAD

**Issue by Bucknalla** [UniversityofWarwick/passport-warwick-sso-oauth#2]
Hi - I'm building a tool for a student society (WarwickTECH) to allow students to borrow hardware, e.g. microcontrollers, electronics, etc. from the society and I was wondering how to generate a Warwick SSO Key & Secret for my application?

It'd be really valuable to use this as we want to allow students to 'sign out' hardware from a web application!

**Comment by matmannion** [comment]
Hi Alex,

I see you've found the form to register for an OAuth consumer key and secret.

You may wish to consider using a supported standard for authentication that's supported at the University such as [Shibboleth](https://shibboleth.net/) - that is more supported than this mechanism which is based on the deprecated OAuth 1.0a.

Our support team will be in touch about what you're trying to achieve and to sort your consumer key and secret out if OAuth is the best route.

Kind regards,

Mat

**Comment by Bucknalla** [comment]
Fantastic, thanks!
